app/routes.py
from flask import (
    render_template,
    flash,
    redirect,
    url_for,
    request,
    make_response,
    Blueprint,
)
from flask_login import current_user, login_user, logout_user, login_required
from app import db
from app.models import User, Survey, Question, Response
from app.forms import (
    LoginForm,
    RegistrationForm,
    CreateSurveyForm,
    AddQuestionForm,
    SurveyResponseForm,
)
from werkzeug.urls import url_parse
import csv
from io import StringIO

bp = Blueprint("routes", __name__)


@bp.route("/")
@bp.route("/index")
def index():
    is_admin = False
    surveys = Survey.query.order_by(Survey.timestamp.desc()).all()
    if current_user.is_authenticated:
        is_admin = current_user.is_admin  # Check if the current user is an admin
    return render_template(
        "index.html", title="Home", surveys=surveys, is_admin=is_admin
    )


@bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("routes.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("routes.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("routes.index")
        return redirect(next_page)
    return render_template("login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("routes.index"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("routes.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        if User.query.count() == 0:
            user.is_admin = True
        db.session.add(user)
        db.session.commit()
        flash("Congratulations, you are now a registered user!")
        return redirect(url_for("routes.login"))
    return render_template("register.html", title="Register", form=form)


@bp.route("/create_survey", methods=["GET", "POST"])
@login_required
def create_survey():
    form = CreateSurveyForm()
    if form.validate_on_submit():
        survey = Survey(title=form.title.data, author=current_user)
        db.session.add(survey)
        db.session.commit()
        flash("Your survey is now live!")
        return redirect(url_for("routes.add_questions", survey_id=survey.id))
    return render_template("create_survey.html", title="Create Survey", form=form)


@bp.route("/survey/<int:survey_id>", methods=["GET", "POST"])
@login_required
def survey(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    form = AddQuestionForm()
    if form.validate_on_submit():
        question = Question(
            text=form.question_text.data,
            input_type=form.input_type.data,
            input_length=form.input_length.data,
            survey=survey,
        )
        db.session.add(question)
        db.session.commit()
        flash("Your question has been added to the survey.")
        return redirect(url_for("routes.survey", survey_id=survey.id))
    questions = survey.questions.all()
    return render_template(
        "survey.html", title=survey.title, survey=survey, form=form, questions=questions
    )


@bp.route("/take_survey/<int:survey_id>", methods=["GET", "POST"])
@login_required
def take_survey(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    questions = survey.questions.all()
    form = SurveyResponseForm()
    if current_user.is_authenticated or survey.is_anonymous:
        if request.method == "POST":
            for question in questions:
                response_text = request.form.get(f"question_{question.id}")
                response = Response(
                    user_id=current_user.id,
                    question_id=question.id,
                    response_text=response_text,
                )
                db.session.add(response)
                db.session.commit()
            flash("Your survey responses have been recorded.")
            return redirect(url_for("routes.index"))
    else:
        flash("You must be logged in to take this survey.")
        return redirect(url_for("routes.login"))
    return render_template(
        "take_survey.html",
        title=survey.title,
        survey=survey,
        questions=questions,
        form=form,
    )


@bp.route("/view_results/<int:survey_id>")
@login_required
def view_results(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    if not current_user.is_admin:
        flash("You do not have permission to view the results.")
        return redirect(url_for("routes.index"))
    questions = survey.questions.all()
    return render_template(
        "view_results.html", title=survey.title, survey=survey, questions=questions
    )


@bp.route("/export_csv/<int:survey_id>")
@login_required
def export_csv(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    if not current_user.is_admin:
        flash("You do not have permission to export the data.")
        return redirect(url_for("routes.index"))
    questions = survey.questions.all()
    si = StringIO()
    cw = csv.writer(si)
    headers = ["Username", "Question", "Response"]
    cw.writerow(headers)
    for question in questions:
        responses = question.responses.all()
        for response in responses:
            user = User.query.get(response.user_id)
            cw.writerow([user.username, question.text, response.response_text])
    output = make_response(si.getvalue())
    output.headers[
        "Content-Disposition"
    ] = f"attachment; filename=survey_{survey_id}_results.csv"
    output.headers["Content-type"] = "text/csv"
    return output


@bp.route("/add_questions/<int:survey_id>", methods=["GET", "POST"])
@login_required
def add_questions(survey_id):
    survey = Survey.query.get_or_404(survey_id)
    form = AddQuestionForm()
    if form.validate_on_submit():
        question = Question(text=form.question_text.data, survey_id=survey.id)
        db.session.add(question)
        db.session.commit()
        if form.add_another.data:
            return redirect(url_for("routes.add_questions", survey_id=survey.id))
        else:
            return redirect(url_for("routes.index"))
    return render_template(
        "add_questions.html", title="Add Questions", form=form, survey=survey
    )

# TODO: add an option to remove questions from a survey when editing
# TODO: add an option to edit questions when editing a survey
# TODO: add an option to delete surveys
# TODO: add add simple data visualization to view_results
# TODO: create an abstract class to hold various demographic questions inherited by a survey class to be asked at the beginning of a survey
# TODO: create a form to choose the fields to be included in the demographic questions

app/templates/add_questions.html
{% extends "base.html" %} {% block content %}
<h1>Add Questions to {{ survey.title }}</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.question_text.label }} {{ form.question_text(class="form-control")
    }}
  </div>
  <div class="form-group">
    {{ form.input_type.label }} {{ form.input_type(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.input_length.label }} {{ form.input_length(class="form-control") }}
  </div>
  {{ form.add_another.label }} {{ form.add_another() }}
  <button type="submit" class="btn btn-primary">Add Question</button>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" />
  <title>{% block title %}{% endblock %} - MVP App</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('routes.index') }}">MVP App</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.create_survey') }}">Create Survey</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.logout') }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.register') }}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">{{ message }}</div>
    {% endfor %} {% block content %}{% endblock %}
  </div>
</body>

</html>

app/templates/create_survey.html
{% extends "base.html" %} {% block title %}Create Survey{% endblock %} {% block
content %}
<h1>Create Survey</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.title.label }} {{ form.title(class="form-control") }} {{form.is_anonymous}}
    {{form.is_anonymous.label}}
  </div>
  <button type="submit" class="btn btn-primary">Create Survey</button>
</form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1>Available Surveys</h1>
<ul class="list-group">
  {% for survey in surveys %}
  {% if survey.is_anonymous and not current_user.is_authenticated %}
  <li><a href="{{ url_for('routes.take_survey', survey_id=survey.id) }}">{{ survey.title }}</a></li>
  {% endif %}
  <li class="list-group-item">
    <a href="{{ url_for('routes.take_survey', survey_id=survey.id) }}">{{ survey.title }}</a>
    {% if current_user.is_admin %}
    <a href="{{ url_for('routes.view_results', survey_id=survey.id) }}" class="float-right">View Results</a>
    <a href="{{ url_for('routes.survey', survey_id=survey.id) }}" class="float-right mr-3">Edit Survey</a>
    <a href="{{ url_for('routes.export_csv', survey_id=survey.id) }}" class="float-right mr-3">Export CSV</a>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block title %}Sign In{% endblock %} {% block
content %}
<h1>Sign In</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.username.label }} {{ form.username(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.password.label }} {{ form.password(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.remember_me(class="form-check-input") }} {{
    form.remember_me.label(class="form-check-label") }}
  </div>
  <button type="submit" class="btn btn-primary">Sign In</button>
</form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %} {% block title %}Register{% endblock %} {% block
content %}
<h1>Register</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.username.label }} {{ form.username(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.password.label }} {{ form.password(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.password2.label }} {{ form.password2(class="form-control") }}
  </div>
  <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}

app/templates/survey.html
{% extends "base.html" %} {% block title %}{{ survey.title }}{% endblock %} {%
block content %}
<h1>{{ survey.title }}</h1>
<h2>Questions</h2>
<ul class="list-group">
  {% for question in questions %}
  <li class="list-group-item">{{ question.text }}</li>
  {% endfor %}
</ul>
<h2>Add Question</h2>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.question_text.label }} {{ form.question_text(class="form-control")
    }}
  </div>
  <div class="form-group">
    {{ form.input_type.label }} {{ form.input_type(class="form-control") }}
  </div>
  <div class="form-group">
    {{ form.input_length.label }} {{ form.input_length(class="form-control") }}
  </div>
  <button type="submit" class="btn btn-primary">Add Question</button>
</form>
{% endblock %}

app/templates/take_survey.html
{% extends "base.html" %} {% block title %}Take Survey{% endblock %} {% block
content %}
<h1>{{ survey.title }}</h1>
<form action="" method="post" novalidate>
  {{ form.hidden_tag() }} {% for question in questions %}
  <div class="form-group">
    <label>{{ question.text }}</label>
    <input
      type="{{ question.input_type }}"
      name="question_{{ question.id }}"
      class="form-control"
      maxlength="{{ question.input_length }}"
      required
    />
  </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Submit Survey</button>
</form>
{% endblock %}

app/templates/view_results.html
{% extends "base.html" %} {% block title %}View Results{% endblock %} {% block
content %}
<h1>{{ survey.title }} - Results</h1>
<ul class="list-group">
  {% for question in questions %}
  <li class="list-group-item">
    <strong>{{ question.text }}</strong>
    <ul>
      {% for response in question.responses %}
      <li>
        {% if response.user %} {{ response.user.username }}: {% endif %}
        {{ response.response_text }}
      </li>
      {% endfor %}
    </ul>
  </li>
  {% endfor %}
</ul>
{% endblock %}